framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors: { log: true }
    session: { enabled: false }
    property_info: { with_constructor_extractor: true }
    serializer: { enabled: true }
    validation: { email_validation_mode: html5 }
    rate_limiter:
        api_anonymous:
            policy: sliding_window
            limit: 100
            interval: '60 minutes'
        api_authenticated:
            policy: sliding_window
            limit: 1000
            interval: '60 minutes'

when@test:
    framework:
        test: true
