apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lexplatform.fullname" . }}-backend
  labels: {{- include "lexplatform.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lexplatform.fullname" . }}-frontend
  labels: {{- include "lexplatform.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
