{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lexplatform.fullname" . }}-secrets
  labels: {{- include "lexplatform.labels" . | nindent 4 }}
type: Opaque
stringData:
  appSecret: {{ .Values.secrets.appSecret | quote }}
  jwtPassphrase: {{ .Values.secrets.jwtPassphrase | quote }}
  liqpayPublicKey: {{ .Values.secrets.liqpayPublicKey | quote }}
  liqpayPrivateKey: {{ .Values.secrets.liqpayPrivateKey | quote }}
  databasePassword: {{ .Values.secrets.databasePassword | quote }}
  rabbitmqPassword: {{ .Values.secrets.rabbitmqPassword | quote }}
{{- end }}
